modLoader="javafml"
loaderVersion="[37,)"
license="GNU LGPLv3"
[[mods]]
modId="fancyicecream"
version="${file.jarVersion}"
displayName="Fancy Ice Cream"
description='''
A mod to add some fancy ice cream items.
'''
[[dependencies.fancyicecream]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.fancyicecream]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,)"
    ordering="NONE"
    side="BOTH"
